[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[omspy-brokers]
name = "omspy-brokers"
version = "0.2.3"
description = ""
authors = ["darkseid <uberdeveloper001@gmail.com>"]
